### ISSUE TITLE
External dependencies support.

### ISSUE THREAD

**Issue by Gonzih** [skuro/lein-misaki#4]
Hi, is it possible to use external dependencies with this plugin? I need to use cheshire for example and only way to achieve this with misaki is to fork and use forked version of misaki. Also is there any support for resources or anything like that? Thanks!

**Comment by skuro** [comment]
It is actually possible: as described in the README, you just need to add the following in your `profiles.clj` configuration:

```
:misaki-dependencies [[your-dependency "1.0.0"]]
```

My `profiles.clj` looks like the following:

```
{:user {:plugins [...]
        :misaki-dependencies [[misaki-clostache "0.0.3-alpha"]]}}
```

**Comment by Gonzih** [comment]
Cool, will it work with non misaki related library (I need cheshire for
example)?

On Tue, May 27, 2014 at 06:12:36AM -0700, Carlo Sciolla wrote:

> It is actually possible: as described in the README, you just need to add the following in your `profiles.clj` configuration:
> 
> ```
> :misaki-dependencies [[your-dependency "1.0.0"]]
> ```
> 
> My `profiles.clj` looks like the following:
> 
> ```
> {:user {:plugins [...]
>         :misaki-dependencies [[misaki-clostache "0.0.3-alpha"]]}}
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/skuro/lein-misaki/issues/4#issuecomment-44273679

## 

Best regards,
Max

**Comment by skuro** [comment]
Sure, if you look at [the implementation](https://github.com/skuro/lein-misaki/blob/master/src/leiningen/misaki.clj#L29) it's just using pomegranate to load new dependencies into the running classpath.

**Comment by Gonzih** [comment]
Ok, thank you for the information! I will try it later.

On Tue, May 27, 2014 at 08:20:51AM -0700, Carlo Sciolla wrote:

> Sure, if you look at [the implementation](https://github.com/skuro/lein-misaki/blob/master/src/leiningen/misaki.clj#L29) it's just using pomegranate to load new dependencies into the running classpath.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/skuro/lein-misaki/issues/4#issuecomment-44290752

## 

Best regards,
Max
